version: '3.3'
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./mongo_data:/data/db